# fly.toml app configuration file generated for still-waterfall-2741 on 2023-09-30T20:50:13Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "still-waterfall-2741"
primary_region = "ord"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
